version: '3.3'
services:
 db:
    image: mysql:5.7
    volumes:
      - my-db:/var/lib/mysql
    environment:
      MYSQL_DATABASE: 'pratice'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'root'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'root'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '4406:3306'
    expose:
      # Opens port 3306 on the container
      - '4406'
      # Where our data will be persisted
    networks:
            testing_net:
                ipv4_address: 172.28.1.1

 employee:
    build:
           context: .
           dockerfile: Dockerfile
    networks:
            testing_net:
                ipv4_address: 172.28.1.2
    ports: 
     - '8009:8080'
volumes:
  my-db:
networks:
    testing_net:
        ipam:
            driver: default
            config:
                - subnet: 172.28.0.0/16
    
